### ISSUE TITLE
Wrong pathways in example?

### ISSUE THREAD

**Issue by chem-william** [UCL-CCS/TIES_MD#5]
Am I crazy in thinking that the figure in https://ucl-ccs.github.io/TIES_MD/theory.html
![image](https://github.com/UCL-CCS/TIES_MD/assets/24978628/1eeb4bb4-46d8-47c6-ad13-edf4c9d67245)
is labelled wrongly? Right now it's showing that `Lambda sterics disappear` is 1.0 while `Lambda electrostatics disappear` is 0.0.

Shouldn't the graph look something like this?:
![image](https://github.com/UCL-CCS/TIES_MD/assets/24978628/fdd648f7-38fa-4ae2-8a0f-2a7010558f15)

Maybe I'm misunderstanding something. If not, I'd be happy to submit a change :-)

**Comment by adw62** [comment]
Yes you are right, good spot the labels on the legend are wrong. Electrostatics disappear and appear should be swapped like so:

```
Lambda sterics disappear: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.6, 0.4, 0.2, 0.1, 0.0]
Lambda sterics appear: [0.0, 0.1, 0.2, 0.4, 0.6, 0.8, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
Lambda electrostatics disappear: [1.0, 0.9, 0.8, 0.6, 0.4, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
Lambda electrostatics appear: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.4, 0.6, 0.8, 0.9, 1.0]
```
